spring:
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: 
            client-secret: 
            provider: custom
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            redirect-uri: http://localhost:8080/api/v1/test
        provider:
          custom:
            authorization-uri: 
            token-uri: 
            user-info-uri: 
          
  thymeleaf:
    cache: false
      
      